import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="application-name" content="CyberPay" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="CyberPay" />
        <meta name="description" content="Pay on Cyber just like Web2" />
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover'
        />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-config" content="/icons/browserconfig.xml" />
        <meta name="msapplication-TileColor" content="#2B5797" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#000000" />

        <link rel="apple-touch-icon" href="/icons/touch-icon-iphone.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/assets/logo-152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/logo-180.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/assets/logo-167.png" />

        <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo-32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/logo-16.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#5bbad5" />
        <link rel="shortcut icon" href="/favicon.ico" />

        <link rel='apple-touch-startup-image' href='/assets/logo-2048.png' sizes='2048x2732' />
        <link rel='apple-touch-startup-image' href='/assets/logo-1668.png' sizes='1668x2224' />
        <link rel='apple-touch-startup-image' href='/assets/logo-1536.png' sizes='1536x2048' />
        <link rel='apple-touch-startup-image' href='/assets/logo-1125.png' sizes='1125x2436' />
        <link rel='apple-touch-startup-image' href='/assets/logo-1242.png' sizes='1242x2208' />
        <link rel='apple-touch-startup-image' href='/assets/logo-750.png' sizes='750x1334' />
        <link rel='apple-touch-startup-image' href='/assets/logo-640.png' sizes='640x1136' />
      </head>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
